// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using estagio_brg.Entities;

namespace estagio_brg.Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("estagio_brg.Entities.Models.Colaborador", b =>
                {
                    b.Property<Guid>("IdColaborador")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdColaborador");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("estagio_brg.Entities.Models.Habilidade", b =>
                {
                    b.Property<Guid>("IdHabilidade")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdHabilidade");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("estagio_brg.Entities.Models.Trilha", b =>
                {
                    b.Property<Guid>("IdTrilha")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdColaborador");

                    b.Property<Guid>("Idhabilidade");

                    b.Property<DateTime>("Prazo");

                    b.HasKey("IdTrilha");

                    b.HasIndex("IdColaborador");

                    b.HasIndex("Idhabilidade");

                    b.ToTable("Trilhas");
                });

            modelBuilder.Entity("estagio_brg.Entities.Models.Trilha", b =>
                {
                    b.HasOne("estagio_brg.Entities.Models.Colaborador", "Colaborador")
                        .WithMany("Trilhas")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("estagio_brg.Entities.Models.Habilidade", "Habilidade")
                        .WithMany("Trilhas")
                        .HasForeignKey("Idhabilidade")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
